# Generated by Django 2.2.16 on 2021-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='timezone',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
