# Generated by Django 2.2.16 on 2021-03-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
