# Generated by Django 2.2.16 on 2021-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0002_planner_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
