# Generated by Django 2.2.16 on 2021-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0003_planner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='paid',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
