# Generated by Django 2.2.16 on 2021-07-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0003_auto_20210706_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
