# Generated by Django 2.2.16 on 2021-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0004_auto_20210706_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='time',
            field=models.TextField(blank=True),
        ),
    ]
