# Generated by Django 2.2.16 on 2021-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0004_planner_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='paid',
            field=models.CharField(choices=[('NP', 'No Payment'), ('PTCA', 'Paid To Clear Ads'), ('PTGS', 'Paid To Get SMS')], max_length=1),
        ),
        migrations.AlterField(
            model_name='planner',
            name='timezone',
            field=models.CharField(max_length=5),
        ),
    ]
