# Generated by Django 2.2.16 on 2021-07-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0005_auto_20210706_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='planit',
        ),
    ]
