# Generated by Django 2.2.16 on 2021-07-13 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planitapp', '0006_delete_planit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='time',
        ),
        migrations.AlterField(
            model_name='planner',
            name='account',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
